services:
  mysql:
    image: "mysql"
    container_name: "mysql-server01"
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
volumes:
  mysql-data:
    driver: local
